package org.geworkbench.components.alignment.blast;

/**
 * <p>Title: </p>
 *
 * <p>Description: </p>
 *
 * <p>Copyright: Copyright (c) 2005</p>
 *
 * <p>Company: </p>
 *
 * @author not attributable
 * @version 1.0
 */

import java.io.*;
import java.util.*;
import java.util.regex.*;

import org.geworkbench.components.alignment.blast.BlastObj;
import org.geworkbench.components.alignment.blast.ProtSeq;
import org.geworkbench.bison.datastructure.biocollections.sequences.
        CSSequenceSet;

import java.net.URL;

/**
 * BlastParser is a class that reads in from a text file generated by
 * RemoteBlast of Blast results.  It parses out the Blast hits into a
 * Vector of BlastObj objects.
 */
public class NCBIBlastParser {

    /**
     * The sequence data used as query seqeunce.
     */
    private CSSequenceSet sequenceDB;
    /**
     * A Vector of Strings representing each Blast hit by Accession number.
     */
    private Vector hits;
    /**
     * The file name to write results out to.
     */
    private String filename;
    /**
     * The default file name to write results out to.
     */
    private final String DEFAULT_FILENAME = "BLAST_results.txt";
    /**
     * An array of type char.
     */
    private final char[] EMPTY = new char[60];

    /**
     * Creates a new BlastParser with querySeq set to specified ProtSeq.
     * Also creates a new hits Vector and sets filename to default value.
     *
     * @param the ProtSeq to set querySeq to.
     */
    public NCBIBlastParser(ProtSeq seq) {
        this.sequenceDB = null;
        hits = new Vector();
        this.filename = DEFAULT_FILENAME;
    }

    /**
     * Creates a new BlastParser with querySeq and filename set to specified
     * ProtSeq and String value.  Also creates a new hits Vector.
     *
     * @param the ProtSeq to set querySeq to.
     * @param the String to set filename to.
     */
    public NCBIBlastParser(CSSequenceSet sequenceDB, String filename) {
        this.sequenceDB = sequenceDB;
        totalSequenceNum = sequenceDB.size();
        hits = new Vector();
        this.filename = filename;
    }

    public NCBIBlastParser(String aString) {
        filename = aString;
        hits = new Vector();
        totalSequenceNum = 1;
    }


    /**
     * Creates a new BlastParser with filename set to default value.  Also
     * creates a new hits Vector.
     */
    public NCBIBlastParser() {
        this.filename = DEFAULT_FILENAME;
        hits = new Vector();
    }

    /**
     * The primary protein sequence, if used as query seqeunce.
     */
    private ProtSeq querySeq;
    static String NEWLINESIGN = "<BR>";
    static String LINEBREAK = "\n";
    static int MAXNUMBERHITS = 250;
    private int hitCount = 0;
    private int totalHitCount = 0;
    private int totalSequenceNum = 0;
    private boolean hit250More = false;


    /**
     * The new BlastDataSet Array
     */
    private ArrayList blastDataset = new ArrayList(10);
    private int count = 0;

    /**
     * Creates a new BlastParser with querySeq and filename set to specified
     * ProtSeq and String value.  Also creates a new hits Vector.
     *
     * @param the ProtSeq to set querySeq to.
     * @param the String to set filename to.
     */
//        public BlastParser(ProtSeq seq, String filename) {
//            querySeq = seq;
//            hits = new Vector();
//            this.filename = filename;
//        }

//        /**
//         * Creates a new BlastParser with filename set to default value.  Also
//         * creates a new hits Vector.
//         */
//        public BlastParser() {
//            this.filename = DEFAULT_FILENAME;
//            hits = new Vector();
//        }

//        /**
//         * BlastParser
//         *
//         * @param aString String
//         */
//        public BlastParser(String aString) {
//            filename = aString;
//            hits = new Vector();
//        }
//

    /**
     * Returns the hits Vector.
     */
    public Vector getHits() {
        return hits;
    }

    public int getHitCount() {
        return hitCount;
    }

    public ArrayList getBlastDataset() {
        return blastDataset;
    }

    public int getTotalSequenceNum() {
        return totalSequenceNum;
    }

    /**
     * Reads in Blast results from file and parses data into BlastObj objects.
     */
    public boolean parseResults() {
        totalHitCount = 0;
        StringTokenizer st;
        BlastObj each;
        String[] fields;
        int index = 0, index2 = 0, start = 0;
        String query = "", subject = "", align = "";
        String errorline = "";

        try {
            File file = new File(filename);
            //server failure
            if (file.length() < 600) {
                System.out.println("No hit found. try again.");
                return false;
            } else {

                //new BufferedReader for parsing file line by line
                BufferedReader br = new BufferedReader(new FileReader(
                        filename));
                String line;
                String sub;
                line = br.readLine();
                do {
                    hits = new Vector();
                    String noResult = "No significant similarity found.";
                    boolean noHitsFound = false;
                    //loop to proceed to beginning of hit list from Blast output file
                    while (true) {
                        line = br.readLine();
                        // System.out.println("test2: " + line);

                        if (line == null ||
                                (line.startsWith(
                                        "Sequences producing significant alignments:"))) {
                            break;
                        }
                        if (line == null ||
                                (line.contains("No significant similarity found."))) {
                            noHitsFound = true;
                            break;
                        }
                    }
                    if (!noHitsFound) {

                        /* parsing section of the blast Hit info text*/
                        br.readLine();
                        line = br.readLine();
                        hitCount = 0;
                        while (line != null &&
                                !line.trim().startsWith("</pre>")) {
                            // System.out.println("test3: " + line);
                            String[] strA = line.split("</a>");

                            for (int i = 0; i < strA.length; i++) {
                                //System.out.println(strA[i]);
                            }
                            hitCount++;
                            totalHitCount++;
                            if (hitCount <= MAXNUMBERHITS) {

                                each = new BlastObj(); //create new BlastObj for hit
                                if (strA.length < 3) {
                                    each.setRetriveWholeSeq(false);
                                } else {
                                    each.setRetriveWholeSeq(true);
                                    StringTokenizer st1 = new StringTokenizer(
                                            strA[
                                                    0], "\"");
                                    st1.nextToken();
                                    if (st1.hasMoreTokens()) {
                                        String s = st1.nextToken();
                                        each.setInfoURL(new URL(s));
                                        s = s.replaceAll("GenPept", "fasta");
                                        s = s.replaceAll("GenBank", "fasta");
                                        each.setSeqURL(new URL(s));

                                    }
                                    if (st1.hasMoreTokens()) {
                                        StringTokenizer st2 = new
                                                StringTokenizer(
                                                st1.nextToken(), "|");
                                        if (st2.hasMoreTokens()) {
                                            each.setDatabaseID(st2.nextToken().
                                                    substring(2));
                                        }
                                        if (st2.hasMoreTokens()) {
                                            each.setName(st2.nextToken());
                                        }
                                        if (st2.hasMoreTokens()) {
                                            each.setDescription(st2.nextToken());
                                        }
                                    }
                                    StringTokenizer st3 = new StringTokenizer(
                                            strA[
                                                    1], "<");
                                    if (st3.hasMoreTokens()) {
                                        each.setDescription(st3.nextToken());
                                    }
                                    if (st3.hasMoreTokens()) {
                                        StringTokenizer st4 = new
                                                StringTokenizer(
                                                st3.nextToken(), ">");

                                        String str = "0";
                                        while (st4.hasMoreTokens()) {
                                            str = st4.nextToken();
                                        }
                                        each.setScore(new Float(str.trim()).
                                                intValue()
                                        );
                                    }
                                    each.setEvalue(strA[2]);

                                    hits.add(each);
                                }
                                //System.out.println(each.getDatabaseID() + each.getDescription()
                                //                   + each.getEvalue() + each.getScore());
                            } else {
                                hit250More = true;
                            }
                            //end of check hitCount;
                            line = br.readLine();

                        } //end of processing summary.
                        //System.out.println(line+ " " + hits.size());
                        index = 0;
                        line = br.readLine();
                        line = br.readLine();
                        if (line == null) {
                            return false;
                        }
                        boolean endofResult = false;
                        while (line != null && !line.trim().startsWith("<pre><script") &&
                                !line.trim().startsWith(">")) {
                            line = br.readLine();
                        }
                        /* parsing detailed alignments Each has <PRE></PRE> */
                        while (line.trim().startsWith("<pre><script") ||
                                line.trim().startsWith(">")) {
                            //System.out.println("test5" + line);
                            if (line.trim().startsWith("</pre></div>")) {
                                endofResult = true;
                                break;
                            }

                            String detaillines = "<PRE>" + line;
                            line = br.readLine().trim();
//                                if (line.trim().startsWith("Database:")) {
//                                    //end of the useful information for one blast.
//                                    endofResult = true;
//                                    break;
//                                }

                            boolean additionalDetail = false;
                            if (line.trim().startsWith("Score")) {
                                index--;
                                additionalDetail = true;

                            }
                            //System.out.println("index"  + index + " " + hits.size());

                            //get BlastObj hit for which alignment is for
                            //System.out.println(index + " = index " + line);
                            each = (BlastObj) hits.get(index);

                            if (count > 60) {
                                //System.out.println(count);
                            }
                            //System.out.println(each.getName());
                            //skip the beginning description
                            subject = "";
                            boolean getStartPoint = true;
                            subject = "";
                            int endPoint = 0;
                            while (!(line.trim().startsWith(">"))) {

                                if (line.startsWith("</pre></div>")) {
                                    //end of the useful information for one blast.
                                    endofResult = true;
                                    break;
                                }

                                if (line.startsWith("Length=")) {
                                    String[] lengthVal = line.split("=");
                                    each.setLength(new Integer(lengthVal[1].trim()).intValue());
                                }
                                if (line.startsWith("Identities = ")) {
                                    /**todo
                                     * use Matchs pattern later.
                                     */
                                    StringTokenizer st1 = new StringTokenizer(
                                            line,
                                            "(");
                                    st1.nextToken();
                                    String identity = st1.nextToken();
                                    String[] s = identity.split("%");
                                    each.setPercentAligned(new Integer(s[0]).
                                            intValue());

                                }
                                // get the start point, end point and length

                                if (line.trim().startsWith("Sbjct")) {
                                    st = new StringTokenizer(line);
                                    st.nextToken();
                                    if (getStartPoint) {
                                        each.setStartPoint(Integer.valueOf(st.
                                                nextToken()).intValue());
                                        getStartPoint = false;
                                    } else {
                                        st.nextToken();
                                    }
                                    //concat the aligned parts and get rid of "-"
                                    subject = subject.concat(st.nextToken().
                                            replaceAll("-", ""));

                                    endPoint = Integer.valueOf(st.nextToken()).
                                            intValue();
                                }

                                //System.out.println(each.getStartPoint() + "" + each.getEndPoint());
                                String s = br.readLine();
                                line = s.trim();
                                if (!line.startsWith(">")) {
                                    detaillines += s + NEWLINESIGN;
                                }
                            }
                            each.setEndPoint(endPoint);
                            each.setAlignmentLength(Math.abs(each.getStartPoint() -
                                    each.getEndPoint()) + 1);
                            each.setSubject(subject);
                            //System.out.println("sub" + subject);

                            detaillines += "</PRE>";

                            //System.out.println(detaillines);
                            if (additionalDetail) {
                                String previousDetail = each.
                                        getDetailedAlignment();
                                detaillines = previousDetail + detaillines;
                            }
                            each.setDetailedAlignment(detaillines);
//                                br.readLine();
//                                br.readLine();
//                                line = br.readLine();

                            index++;
                            if (endofResult) {
                                endofResult = false;
                                break;
                            }

                        }
                        line = br.readLine();
                        Vector newHits = hits;
                        blastDataset.add(newHits);
                        count++;
//                        System.out.println("run ps" + count + blastDataset.size() +
//                                           " " + newHits.size());
                    } else {
                        blastDataset.add(null);
                        count++;
                        // System.out.println("Found 1 nohits" + count);
                    }
                } while (count < totalSequenceNum);
                //  System.out.println("run out of ps" + count + blastDataset.size());
                return true;
            }

        } catch (FileNotFoundException e) {
            System.out.println("file not found.");
            return false;
            //System.exit(1);
        } catch (IOException e) {
            System.out.println("NCBIBLASTParser + IOException!");
             e.printStackTrace();
            return false;
        } catch (Exception e) {

            System.out.println("NCBIBLASTParser " + errorline);
            e.printStackTrace();

            //find a blast bug, temp change to true.
            return false;

        }

    }

    public void setHitCount(int hitCount) {
        this.hitCount = hitCount;
    }

    public void setBlastDataset(ArrayList blastDataset) {
        this.blastDataset = blastDataset;
    }

    public void setTotalSequenceNum(int totalSequenceNum) {
        this.totalSequenceNum = totalSequenceNum;
    }

    /**
     * getSummary
     *
     * @return String
     */
    public String getSummary() {
        if (hit250More) {
            return "Some sequences have more than 250 hits, only the first 250 hits are displayed. Total hits are " +
                    totalHitCount +
                    ".";
        }
        return "Total hits for all sequences are " + totalHitCount + ".";
    }

     public static void main(String[] args) {

            BlastParser test = new BlastParser();
        // test.filename = "C:\\Blast-1992809694.html";
         test.filename = "C:\\gforge\\geworkbench\\temp\\GEAW\\Blast1374003213.html";
            test.parseResults();
             }


}
