package org.geworkbench.components.mindy;

import java.io.Serializable;
import java.util.ArrayList;

import org.geworkbench.bison.datastructure.bioobjects.markers.DSGeneMarker;

/**
 * @author oshteynb
 * @version $Id: ModulatorSelections.java,v 1.3 2009-04-29 19:55:33 oshteynb Exp $
 *
 */
public class ModulatorSelections  implements Serializable{
	/**
	 * 	serialVersionUID generated by Eclipse
	 */
	private static final long serialVersionUID = 7876525672203113336L;

	private MindyPlugin mindyPlugin;
	ModulatorModel modulatorModel;

	// from ModulatorModel
	private ArrayList<DSGeneMarker> selectedModulators;

	public ModulatorSelections(MindyPlugin mindyPlugin,
			ModulatorModel modulatorModel) {
		this.mindyPlugin = mindyPlugin;
		this.modulatorModel = modulatorModel;

		this.selectedModulators = new ArrayList<DSGeneMarker>();
	}

	public ArrayList<DSGeneMarker> getSelectedModulators() {
		return selectedModulators;
	}

	// TODO update in corresponding models
	public void setSelectedModulators(ArrayList<DSGeneMarker> selectedModulators) {
		if (selectedModulators == null) {

			/* clear modulators in tabs */
			this.selectedModulators.clear();

			this.mindyPlugin.aggregateModel.disableAllModulators();

			this.mindyPlugin.modTargetModel.disableAllModulators();
		} else {
			this.selectedModulators = selectedModulators;
		}
	}

	// TODO update in corresponding models
	public void addSelectedModulator(DSGeneMarker mod) {
		this.selectedModulators.add(mod);
	}

}
